enforce_secure_profile: false
listeners:
- query_port: 25565
  motd: '&1EaglercraftX Server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25567
  max_players: 10
  tab_size: 60
  force_default_server: true
remote_ping_cache: 5000
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: false
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: 10
prevent_proxy_connections: false
ip_forward: true
groups: {}
remote_ping_timeout: 3000
connection_throttle: 2000
log_commands: false
stats: b6b0c8f3-e602-4a2e-b09d-0acb68d88c3e
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1EaglercraftX Game Server'
    address: localhost:25566
    restricted: false
